# Generated by Django 4.2.11 on 2025-11-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
